### PR TITLE
Legitify

### PR DESCRIPTION
**Pull request by dcposch**
@Flet

### CODE REVIEW

**Comment by feross** [comment]
+1

**Comment by Flet** [comment]
My goal with this repo (and the reason for the naughty find/replace) was to have the only deviation be semicolons with all other changes automatically inherited from the `standard` module. 

This was done explicity to avoid having a full fork that could potentially deviate further from the standard. Also this avoids maintainence for the most part, falling back on the dependency (not a perfect way to do it, but still less work). 

Thinking this one over...

**Comment by dcposch** [comment]
Check out that second commit, it contains just the semicolon change plus some trolling in the README. I'm thinking we can keep rebasing it in top of the latest `standard`, so we keep the same versions and the same small changeset. Check out the commit message for details on how this works.

**Comment by dcposch** [comment]
PS re "automatically inherited from the standard module", we'd have to publish this module anyway every time standard is published if we want the versions to stay in sync.

**Comment by Flet** [comment]
> we'd have to publish this module anyway every time standard is published if we want the versions to stay in sync

This is not quite true. If the dependency is 2.x.x it will be resolved to the latest minor version at the time  the user installs (I agree this is not perfect).

In any case, the only other solutions I could think of to make this cleaner involve @feross changing `standard` in some way... for example if `standard` had an option to provide a different path for `rc` or had some way of overlaying rc files or overriding individual rules..

Would you be oppose to a PR that added an option to override the path to `rc`, @feross?

**Pull request merged**
