### PR TITLE
Update dep to fix error

### LINKED ISSUE #36: Getting "Definition for rule 'react/jsx-no-duplicate-props' was not found" errors
Using semistandard today all of a sudden results in "Definition for rule 'react/jsx-no-duplicate-props' was not found" errors.

### PR DESCRIPTION
**Pull request by kesla**
Fixes #36 by updating eslint-plugin-react - to the version used by standard already.

### CODE REVIEW

**Comment by OlivierCuyp** [comment]
@Flet Could please merge this PR and fix the standard version in the package.json to avoid this kind of issue in the futur ?

**Comment by Flet** [comment]
Thanks! I'll enable greenkeeper on this repo to try to catch this if it happens again.

**Comment by Flet** [comment]
published as 7.0.3

**Comment by kesla** [comment]
@Flet thanks!

**Comment by ckiss** [comment]
thanks @Flet

**Comment by OlivierCuyp** [comment]
@Flet Thx!

**Pull request merged**
